config/routes.rb
Rails.application.routes.draw do
  get '/price', to: 'paymenttypes#price'
  resources :paymenttypes

  root to: 'visitors#index'
  devise_for :users
  resources :users do
    resources :payments
  end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  has_many :paymenttype
end

app/models/paymenttype.rb
class Paymenttype < ActiveRecord::Base
  belongs_to :payment
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :payments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:name, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) {
          |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) {
          |u| u.permit(registration_params)
      }
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @payments = Payment.all
    respond_with(@payments)
  end

  def show
    respond_with(@payment)
  end

  def new
    @payment = Payment.new
    @types = Hash.new
    Paymenttype.all.each { |t| @types[t.typename] = t.id }
    @payment.user = current_user
    respond_with(@payment,@types)
  end

  def edit
    @types = Hash.new
    Paymenttype.all.each { |t| @types[t.typename] = t.id }
    @payment.user = current_user
    respond_with(@payment,@types)
  end

  def create
    @payment = Payment.new(payment_params)
    @payment.user = current_user
    @payment.save
    respond_with(@payment)
  end

  def update
    @payment.update(payment_params)
    respond_with(@payment)
  end

  def destroy
    @payment.destroy
    respond_with(@payment)
  end

  private
    def set_payment
      @payment = Payment.find(params[:id])
    end

    def payment_params
      params.require(:payment).permit(:paymenttype_id, :start_date, :end_date, :amount, :user)
    end
end

app/controllers/paymenttypes_controller.rb
class PaymenttypesController < ApplicationController
  before_action :set_paymenttype, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @paymenttypes = Paymenttype.all
    respond_with(@paymenttypes)
  end

  def show
    respond_with(@paymenttype)
  end

  def new
    @paymenttype = Paymenttype.new
    respond_with(@paymenttype)
  end

  def price
    price = Paymenttype.all;
    render :json => price
  end

  def edit
  end

  def create
    @paymenttype = Paymenttype.new(paymenttype_params)
    @paymenttype.save
    respond_with(@paymenttype)
  end

  def update
    @paymenttype.update(paymenttype_params)
    respond_with(@paymenttype)
  end

  def destroy
    @paymenttype.destroy
    respond_with(@paymenttype)
  end

  private
    def set_paymenttype
      @paymenttype = Paymenttype.find(params[:id])
    end

    def paymenttype_params
      params.require(:paymenttype).permit(:typename, :price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all

  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/paymenttypes_helper.rb
module PaymenttypesHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>

<nav class="navbar navbar-default" role="navigation">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'Home', root_path, class: 'navbar-brand' %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Add payment', new_user_payment_path(user_id: current_user.id) if current_user %> </li>
      <li><a href="#">Link</a></li>
    </ul>
    <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
    <ul class="nav navbar-nav navbar-right">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Edit payment types', paymenttypes_path %></li>
  <% end %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Platezhka" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Platezhka" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class="container">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </div>
  </body>
</html>

app/views/payments/_edit_form.html.erb
<%= bootstrap_form_for [current_user,@payment], url: user_payments_url do |f| %>
      <%= f.select :paymenttype_id,@types, label: 'Payment type' %>
      <%= f.date_select :start_date %>
      <%= f.date_select :end_date %>
      <%= f.number_field :amount %>

    <%= f.static_control label: "Total" do %>
        <span id="total_sum"></span>
    <% end %>
      <%= f.submit 'Edit payment' %>

<% end %>

<script language="JavaScript">
  var s = new Object();
 $('document').ready(
 function ()
 {
     $.ajax(
             {
                 url: '/price'
             }
     ).done(
             function (data) {
                 console.log(data);
                 s = data;

                 var value = $('#payment_amount').val();
                 var sel_id = $('#payment_paymenttype_id').val();
                 var price = s[sel_id-1].price * value;
                 $('#total_sum').text(price + " сум");

             }
     )
 }
 );
 $('#payment_amount').change(function()
 {
     var value = $('#payment_amount').val();
     var sel_id = $('#payment_paymenttype_id').val();
     var price = s[sel_id-1].price * value;
     $('#total_sum').text(price + " сум");

 });
</script>

app/views/payments/_form.html.erb
<%= bootstrap_form_for [current_user,@payment], url: user_payments_url do |f| %>
      <%= f.select :paymenttype_id,@types, label: 'Payment type' %>
      <%= f.date_select :start_date %>
      <%= f.date_select :end_date %>
      <%= f.number_field :amount %>

    <%= f.static_control label: "Total" do %>
        <span id="total_sum"></span>
    <% end %>
      <%= f.submit 'Add payment' %>

<% end %>
<script language="JavaScript">
  var s = new Object();
 $('document').ready(
 function ()
 {
     $.ajax(
             {
                 url: '/price'
             }
     ).done(
             function (data) {
                 console.log(data);
                 s = data;
             }
     )
 }
 );
 $('#payment_amount').change(function()
 {
     var value = $('#payment_amount').val();
     var sel_id = $('#payment_paymenttype_id').val();
     var price = s[sel_id-1].price * value;
     $('#total_sum').text(price + " сум");

 });
</script>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'edit_form' %>

<%= link_to 'Show', user_payment_path(id: @payment.id, user_id: @payment.user.id) %> |
<%= link_to 'Back', user_payments_path %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table class="table">
  <thead>
    <tr>
      <th>Paymenttype</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Amount</th>
      <!--<th>User</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= Paymenttype.find(payment.paymenttype_id).typename %></td>
        <td><%= payment.start_date %></td>
        <td><%= payment.end_date %></td>
        <td><%= payment.amount %></td>
       <!-- <td><%= payment.user.name %></td>-->
        <td><%= link_to 'Show', user_payment_path(id: payment.id, user_id: payment.user.id) %></td>
        <td><%= link_to 'Edit', edit_user_payment_path(id: payment.id, user_id: payment.user.id) %></td>
        <td><%= link_to 'Destroy', user_payment_path(id: payment.id, user_id: payment.user.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_user_payment_path %>

app/views/payments/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
<h1>New payment</h1>
<%= render 'form' %>

<%= link_to 'Back', user_payments_path %>
</div>
      </div>
    </div>
    </div>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ФИО:</strong>
  <%= @payment.user.name %>
</p>

<p>
  <strong>Тип платежа:</strong>
  <%= Paymenttype.find(@payment.paymenttype_id).typename %>
</p>

<p>
  <strong>За сколько:</strong>
  <%= @payment.amount %>
</p>

<p>
  <strong>Тариф:</strong>
  <span id="tariff"></span>
</p>

<p>
  <strong>Итого:</strong>
  <span id="total_sum"></span>
</p>

<p>
  <strong>С какого числа:</strong>
  <%= @payment.start_date %>
</p>

<p>
  <strong>По какое число:</strong>
  <%= @payment.end_date %>
</p>





<%= link_to 'Edit', edit_user_payment_path(id: @payment.id, user_id: @payment.user.id) %> |
<%= link_to 'Back', user_payments_path(id: @payment.id, user_id: @payment.user.id) %>

<script language="JavaScript">
    var s = new Object();
    $('document').ready(
            function ()
            {
                $.ajax(
                        {
                            url: '/price'
                        }
                ).done(
                        function (data) {
                            console.log(data);
                            s = data;
                            var value = <%= @payment.amount %>;
                            var sel_id = <%= @payment.paymenttype_id %>;
                            var price = s[sel_id-1].price * value;
                            $('#tariff').text(s[sel_id-1].price + " сум");
                            $('#total_sum').text(price + " сум");
                        }
                );


            }
    );




</script>

app/views/paymenttypes/_form.html.erb
<%= simple_form_for(@paymenttype) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :typename %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/paymenttypes/edit.html.erb
<h1>Editing paymenttype</h1>

<%= render 'form' %>

<%= link_to 'Show', @paymenttype %> |
<%= link_to 'Back', paymenttypes_path %>

app/views/paymenttypes/index.html.erb
<h1>Listing paymenttypes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Typename</th>
      <th>Price</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @paymenttypes.each do |paymenttype| %>
      <tr>
        <td><%= paymenttype.typename %></td>
        <td><%= paymenttype.price %></td>
        <td><%= link_to 'Show', paymenttype %></td>
        <td><%= link_to 'Edit', edit_paymenttype_path(paymenttype) %></td>
        <td><%= link_to 'Destroy', paymenttype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paymenttype', new_paymenttype_path %>

app/views/paymenttypes/new.html.erb
<h1>New paymenttype</h1>

<%= render 'form' %>

<%= link_to 'Back', paymenttypes_path %>

app/views/paymenttypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Typename:</strong>
  <%= @paymenttype.typename %>
</p>

<p>
  <strong>Price:</strong>
  <%= @paymenttype.price %>
</p>

<%= link_to 'Edit', edit_paymenttype_path(@paymenttype) %> |
<%= link_to 'Back', paymenttypes_path %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">

    <h3>Users</h3>

      <table class="table">
        <thead>
        <tr>
          <td>Name</td>
          <td>Email</td>
        </tr>
        </thead>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>

      </table>
    </div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>